version: "3.7"

services:
  wiki:
    image: requarks/wiki:2
    restart: unless-stopped
    ports:
      - 80:3000
      - 443:3443
    networks:
      - wikinet
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_PASS_FILE: /etc/wiki/.db-secret
      DB_USER: wiki
      DB_NAME: wiki
      UPGRADE_COMPANION: 1
    volumes:
      - "./wiki/.db-secret:/etc/wiki/.db-secret"
    networks:
      - wikinet
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD_FILE: /etc/wiki/.db-secret
      POSTGRES_USER: wiki
    restart: unless-stopped
    volumes:
      - "./dbdata:/var/lig/postgresql/data"
      - "./wiki/.db-secret:/etc/wiki/.db-secret"
    networks:
      - wikinet
    depends_on:
      - file-server

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db
    networks:
      - wikinet

  wiki-update-companion:
    image: ghcr.io/requarks/wiki-update-companion:latest
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - wikinet
    depends_on:
      - wiki    
    links:
      - db
      - wiki

  file-server:
    build: ./file-server
    restart: unless-stopped
    volumes:
      - "./file-server/data:/var/file-server"
    networks:
      - wikinet
    ports:
      - 8000:8000

networks:  
  wikinet:
