# Create installation directory for Wiki.js
# mkdir -p /etc/wiki
#
# # Generate DB secret
# openssl rand -base64 32 > /etc/wiki/.db-secret
#
# # Create internal docker network
# docker network create wikinet
#
# # Create data volume for PostgreSQL
# docker volume create pgdata
#
# # Create the containers
# docker create --name=db -e POSTGRES_DB=wiki -e POSTGRES_USER=wiki -e POSTGRES_PASSWORD_FILE=/etc/wiki/.db-secret -v /etc/wiki/.db-secret:/etc/wiki/.db-secret:ro -v pgdata:/var/lib/postgresql/data --restart=unless-stopped -h db --network=wikinet postgres:11
# docker create --name=wiki -e DB_TYPE=postgres -e DB_HOST=db -e DB_PORT=5432 -e DB_PASS_FILE=/etc/wiki/.db-secret -v /etc/wiki/.db-secret:/etc/wiki/.db-secret:ro -e DB_USER=wiki -e DB_NAME=wiki -e UPGRADE_COMPANION=1 --restart=unless-stopped -h wiki --network=wikinet -p 80:3000 -p 443:3443 ghcr.io/requarks/wiki:2
# docker create --name=wiki-update-companion -v /var/run/docker.sock:/var/run/docker.sock:ro --restart=unless-stopped -h wiki-update-companion --network=wikinet ghcr.io/requarks/wiki-update-companion:latest
#
#
version: "3.7"

services:
  wiki:
    image: requarks/wiki:2
    restart: unless-stopped
    ports:
      - 80:3000
      - 443:3443
    networks:
      - wikinet
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_PASS_FILE: /etc/wiki/.db-secret
      DB_USER: wiki
      DB_NAME: wiki
      UPGRADE_COMPANION: 1
    volumes:
      - "./wiki/.db-secret:/etc/wiki/.db-secret"
    networks:
      - wikinet

  db:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD_FILE: /etc/wiki/.db-secret
      POSTGRES_USER: wiki
    restart: unless-stopped
    volumes:
      - "./dbdata:/var/lig/postgresql/data"
      - "./wiki/.db-secret:/etc/wiki/.db-secret"
    networks:
      - wikinet

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db
    networks:
      - wikinet

networks:
  wikinet:
